name: Air Québec
title: Air Québec | Qualité de l'air
description: Project sur la qualité de l'air à la ville de Québec
tags:
  - aqi
  - science
  - recherche
show_hero: true
menu:
  - title: Accueil
    url: /
  - title: À propos
    url: /about
  - title: Contact
    url: /contact
  - title: Publications
    url: /feed.xml
email: air@drave.dev
# See: https://disqus.com/
#disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xgedoagy
